# Generated by Django 4.2.5 on 2023-10-05 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0009_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
