# Generated by Django 4.2.5 on 2023-10-24 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_payment_ispaid'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='real_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
