# Generated by Django 4.2.5 on 2023-10-26 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_transaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
