# Generated by Django 4.2.5 on 2023-10-16 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='token',
        ),
    ]
