# Generated by Django 4.2.5 on 2023-10-17 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_booking', '0002_remove_booking_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_Id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
