# Generated by Django 4.2.5 on 2023-10-21 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_booking', '0004_user_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
